[project]
name = "faceforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "numpy>=2.5.2",
    "onnxruntime-gpu[cuda,cudnn]>=1.28.0",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "ultralytics>=8.4.118",
    "uvicorn>=0.52.1",
    "sqlalchemy>=2.0.30",
    "alembic>=1.13.1",
    "asyncpg>=0.29.0",
    "psycopg2-binary>=2.9.9",
    "onnxruntime>=1.28.0",
]
